Bump eslint-plugin-unicorn from 65.0.0 to 67.0.0 (#887)
* Bump eslint-plugin-unicorn from 65.0.0 to 67.0.0

Bumps [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) from 65.0.0 to 67.0.0.
- [Release notes](https://github.com/sindresorhus/eslint-plugin-unicorn/releases)
- [Commits](https://github.com/sindresorhus/eslint-plugin-unicorn/compare/v65.0.0...v67.0.0)

---
updated-dependencies:
- dependency-name: eslint-plugin-unicorn
  dependency-version: 66.0.0
  dependency-type: direct:development
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Upgrade to ESLINT to version 10

- Upgrade Babel packages as well (https://babeljs.io/docs/v8-migration/#:~:text=Remove%20useSpread%20and%20useBuiltIns%20options%20(%2312593))
- Upgrade node version (https://babeljs.io/docs/v8-migration/#:~:text=All%20Babel%208%20packages%20require%20Node%2Ejs%20%5E22%2E18%2E0%20%7C%7C%20%3E%3D24%2E11%2E0%2E%20We%20highly%20encourage%20you%20to%20use%20the%20Active%20LTS%20version%20of%20Node%2Ejs%20%28v24%29%3A%20see%20nodejs%2FRelease%20for%20more%20information)

Error: https://fundraising-ci.wikimedia.de/repos/5/pipeline/3161/3

* Upgrade node to latest LTS version

- https://nodejs.org/en/download

* Update dependencies

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Sperling-0 <tanuja.doriya@wikimedia.de>